# Generated by Django 2.2.4 on 2019-08-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190820_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
